#!/usr/bin/env bash
# Installs an optional git pre-push hook that runs scripts/check.sh when the
# push includes changes under mobile-app/apps/flutter.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOKS_DIR="$(git rev-parse --git-path hooks)"
HOOK="$HOOKS_DIR/pre-push"

cat > "$HOOK" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by mobile-app/apps/flutter/scripts/install-hooks.sh
set -uo pipefail

remote_sha=$(git rev-parse @{push} 2>/dev/null || git merge-base HEAD origin/main 2>/dev/null || echo "")
range="HEAD"
[ -n "$remote_sha" ] && range="$remote_sha..HEAD"

if git diff --name-only "$range" 2>/dev/null | grep -q '^mobile-app/apps/flutter/'; then
  echo "pre-push: Flutter changes detected, running checks..."
  "$(git rev-parse --show-toplevel)/mobile-app/apps/flutter/scripts/check.sh" || {
    echo "pre-push: checks failed. Push aborted (use --no-verify to override)."
    exit 1
  }
fi
exit 0
EOF

chmod +x "$HOOK"
echo "Installed pre-push hook at $HOOK"
